Traceback (most recent call last):
  File "../../../../scFEA/src/scFEA.py", line 374, in <module>
    main(args)
  File "../../../../scFEA/src/scFEA.py", line 117, in main
    moduleGene = pd.read_csv(
  File "/home/kvalem/.conda/envs/scFEA_2024/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kvalem/.conda/envs/scFEA_2024/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kvalem/.conda/envs/scFEA_2024/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/kvalem/.conda/envs/scFEA_2024/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/kvalem/.conda/envs/scFEA_2024/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/module_gene_complete_mouse_m168.csv'
srun: error: apollo-03: task 0: Exited with exit code 1
